AWSTemplateFormatVersion:  "2010-09-09"
Description: "Creates the Autoscaling Group launch configuration"
Parameters:
  DataDogKey:
    Description: "DataDog API Key"
    Type: String
Resources:  
  Document:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content: !Sub |
        {
          "schemaVersion": "2.2",
          "description": "Install Datadog Agent",
          "parameters": {
            "DatadogAPIKey": {
              "type": "String",
              "default": "${DataDogKey}",
              "description": "The datadog API Key"
            }
          },
          "mainSteps": [
            {
              "action": "aws:runShellScript",
              "name": "datadogInstaller",
              "inputs": {
                "runCommand": [
                  "#!/bin/bash",
                  "echo \"Installing Datadog Agent\"",
                  "if [ ! -f /etc/yum.repos.d/datadog.repo ]; then",
                  "  cat <<SOURCE > /etc/yum.repos.d/datadog.repo",
                  "[datadog]",
                  "name = Datadog, Inc.",
                  "baseurl = http://yum.datadoghq.com/rpm/x86_64/",
                  "enabled=0",
                  "gpgcheck=0",
                  "SOURCE",
                  "  yum --enablerepo=datadog -y install datadog-agent",
                  "fi",
                  "sed \"s/api_key:.*/api_key: {{ DatadogAPIKey }}/\" /etc/dd-agent/datadog.conf.example > /etc/dd-agent/datadog.conf",
                  "sed -i \"/# collector_log_file:/ s/# *//\" /etc/dd-agent/datadog.conf",
                  "sed -i \"/# forwarder_log_file:/ s/# *//\" /etc/dd-agent/datadog.conf",
                  "sed -i \"/# dogstatsd_log_file:/ s/# *//\" /etc/dd-agent/datadog.conf",
                  "sed -i \"/# additional_checksd:/ s/# *//\" /etc/dd-agent/datadog.conf",
                  "chkconfig datadog-agent on",
                  "/etc/init.d/datadog-agent start"
                ]
              }
            }
          ]
        }